apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "task-manager.selectorLabels" . | nindent 4}}
    app.kubernetes.io/component: backend
  ports:
  - name: backend-port
    protocol: TCP
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
