apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "task-manager.labels" . | nindent 4}}
data:
  ENVIRONMENT: {{ .Values.backend.config.ENVIRONMENT }}
