apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-pg-ready-check
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: pg-ready-check
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          command: ["sh", "-c", "pg_isready -h {{ .Release.Name }}-postgres -p {{ .Values.postgres.service.targetPort }} -U postgres -d taskdb_prod"]